project_id = "tpgewmfslapicruzgula"

[functions.send-otp]
verify_jwt = true

[functions.verify-otp]
verify_jwt = false

[functions.get-otp-info]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.verify-comprovante]
verify_jwt = false
