project_id = "tpgewmfslapicruzgula"

[functions.send-otp]
verify_jwt = true

[functions.verify-otp]
verify_jwt = false

[functions.get-otp-info]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.verify-comprovante]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true

[functions.registro-imobiliaria]
verify_jwt = false

[functions.registro-corretor-autonomo]
verify_jwt = false

[functions.admin-create-corretor]
verify_jwt = true

[functions.admin-update-corretor]
verify_jwt = true

[functions.admin-reset-corretor-password]
verify_jwt = true

[functions.admin-vincular-usuario]
verify_jwt = true

[functions.admin-get-corretores-emails]
verify_jwt = true

[functions.get-imobiliaria-by-email]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-fix-inconsistencies]
verify_jwt = true

[functions.asaas-create-customer]
verify_jwt = true

[functions.asaas-create-subscription]
verify_jwt = true

[functions.asaas-payment-link]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-cancel-subscription]
verify_jwt = true

[functions.chat-assistente]
verify_jwt = false
